name: Sync EcoMobile Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  sync-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure Git identity
        run: |
          git config user.name "Xybronix"
          git config user.email "xybronix@gmail.com"

      - name: Split backend subtree
        run: |
          git subtree split --prefix=backend -b backend-split
      
      - name: Debug token presence
        run: |
          if [ -z "${{ secrets.ECOMOBILE_SYNC_TOKEN }}" ]; then
            echo "TOKEN IS EMPTY"
            exit 1
          else
            echo "TOKEN IS PRESENT"
          fi

      - name: Verify Git remote
        run: |
          git remote -v

      - name: Push to EcoMobile-backend
        run: |
          git push https://Xybronix:${{ secrets.ECOMOBILE_SYNC_TOKEN }}@github.com/Xybronix/EcoMobile-backend.git backend-split:main --force
